import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUI.java
 *
 * Created on 25-Dec-2010, 3:20:45 PM
 */



public class GUI extends javax.swing.JFrame {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	//Communicator object
    Communicator communicator = null;
    //KeybindingController object
    KeybindingController keybindingController = null;
    public Server server;
    public Thread th;
    private int dataReceivedFromClient=0;
    /** Creates new form GUI */
    public GUI() {
        initComponents();
        createObjects();
        server=new Server(this);
        th=new Thread(server);
        communicator.searchForPorts();
        keybindingController.toggleControls();
        keybindingController.bindKeys();
        
    }


    public int getDataReceivedFromClient() {
		return dataReceivedFromClient;
	}

	public void setDataReceivedFromClient(int dataReceivedFromClient) {
		this.dataReceivedFromClient = dataReceivedFromClient;
		communicator.sendData(dataReceivedFromClient);
	}

	private void createObjects()
    {
        communicator = new Communicator(this);
        keybindingController = new KeybindingController(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @SuppressWarnings({ "rawtypes" })
	private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblLeft = new javax.swing.JLabel();
        btnLeftAccel = new javax.swing.JButton();
        btnLeftDecel = new javax.swing.JButton();
        btnRightAccel = new javax.swing.JButton();
        lblRight = new javax.swing.JLabel();
        btnRightDecel = new javax.swing.JButton();
        cboxPorts = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        btnConnect = new javax.swing.JButton();
        btnDisconnect = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOTUS Server");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("LOTUS Server Control");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Throttle");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Left");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Right");

        lblLeft.setFont(new java.awt.Font("Tahoma", 1, 18));
        lblLeft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLeft.setText("0");

        btnLeftAccel.setText("/\\");
            btnLeftAccel.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnLeftAccelActionPerformed(evt);
                }
            });

            btnLeftDecel.setText("\\/");
            btnLeftDecel.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnLeftDecelActionPerformed(evt);
                }
            });

            btnRightAccel.setText("/\\");
                btnRightAccel.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnRightAccelActionPerformed(evt);
                    }
                });

                lblRight.setFont(new java.awt.Font("Tahoma", 1, 18));
                lblRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblRight.setText("0");

                btnRightDecel.setText("\\/");
                btnRightDecel.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnRightDecelActionPerformed(evt);
                    }
                });

                jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
                jLabel5.setText("Select the COM Port");

                btnConnect.setText("Connect");
                btnConnect.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                    	th.start();
                        btnConnectActionPerformed(evt);
                    }
                });

                btnDisconnect.setText("Disconnect");
                btnDisconnect.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnDisconnectActionPerformed(evt);
                        server.close();
                    }
                });

                jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11));
                jLabel13.setText("Log");
                
                textField = new JTextField();
                textField.setColumns(10);
                txtLog = new javax.swing.JTextArea();
                
                                txtLog.setColumns(20);
                                txtLog.setEditable(false);
                                txtLog.setLineWrap(true);
                                txtLog.setRows(5);
                                txtLog.setFocusable(false);
                
                JButton btnSend = new JButton("Send");
                btnSend.addActionListener(new ActionListener() {
                	public void actionPerformed(ActionEvent arg0) {
                		//int dataOut=dataReceivedFromClient;
                		int dataOut=Integer.valueOf(textField.getText().toString());
                		communicator.sendData(dataOut);
                		
                	}
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                layout.setHorizontalGroup(
                	layout.createParallelGroup(Alignment.LEADING)
                		.addGroup(layout.createSequentialGroup()
                			.addContainerGap()
                			.addGroup(layout.createParallelGroup(Alignment.LEADING)
                				.addComponent(jLabel5)
                				.addComponent(jLabel1)
                				.addGroup(layout.createSequentialGroup()
                					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
                						.addComponent(textField)
                						.addGroup(layout.createSequentialGroup()
                							.addComponent(cboxPorts, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
                							.addPreferredGap(ComponentPlacement.RELATED)
                							.addComponent(btnConnect)))
                					.addPreferredGap(ComponentPlacement.RELATED)
                					.addGroup(layout.createParallelGroup(Alignment.LEADING)
                						.addComponent(btnSend)
                						.addComponent(btnDisconnect)))
                				.addComponent(jLabel2)
                				.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
                					.addGroup(layout.createSequentialGroup()
                						.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
                						.addPreferredGap(ComponentPlacement.RELATED)
                						.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                					.addGroup(layout.createSequentialGroup()
                						.addGroup(layout.createParallelGroup(Alignment.TRAILING)
                							.addGroup(layout.createSequentialGroup()
                								.addComponent(btnLeftAccel)
                								.addPreferredGap(ComponentPlacement.RELATED))
                							.addGroup(layout.createSequentialGroup()
                								.addComponent(lblLeft)
                								.addGap(26)))
                						.addGroup(layout.createParallelGroup(Alignment.LEADING)
                							.addGroup(layout.createSequentialGroup()
                								.addGap(10)
                								.addComponent(lblRight))
                							.addComponent(btnRightAccel))))
                				.addGroup(layout.createSequentialGroup()
                					.addComponent(btnLeftDecel)
                					.addPreferredGap(ComponentPlacement.UNRELATED)
                					.addComponent(btnRightDecel)))
                			.addGap(61)
                			.addGroup(layout.createParallelGroup(Alignment.LEADING)
                				.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
                					.addComponent(jLabel13, Alignment.LEADING)
                					.addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
                				.addComponent(txtLog, GroupLayout.PREFERRED_SIZE, 315, GroupLayout.PREFERRED_SIZE))
                			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                	layout.createParallelGroup(Alignment.LEADING)
                		.addGroup(layout.createSequentialGroup()
                			.addContainerGap()
                			.addComponent(jLabel1)
                			.addPreferredGap(ComponentPlacement.RELATED)
                			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
                				.addComponent(jLabel5)
                				.addComponent(jLabel13))
                			.addPreferredGap(ComponentPlacement.RELATED)
                			.addGroup(layout.createParallelGroup(Alignment.LEADING)
                				.addComponent(jScrollPane2, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                				.addGroup(layout.createSequentialGroup()
                					.addGroup(layout.createParallelGroup(Alignment.LEADING)
                						.addGroup(layout.createSequentialGroup()
                							.addGroup(layout.createParallelGroup(Alignment.LEADING)
                								.addComponent(cboxPorts, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                								.addComponent(btnConnect))
                							.addGap(18)
                							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
                								.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                								.addComponent(btnSend))
                							.addGap(13)
                							.addComponent(jLabel2)
                							.addGap(9)
                							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
                								.addComponent(jLabel3)
                								.addComponent(jLabel4))
                							.addGap(11)
                							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
                								.addComponent(btnLeftAccel)
                								.addComponent(btnRightAccel))
                							.addGap(9)
                							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
                								.addComponent(lblLeft)
                								.addComponent(lblRight))
                							.addGap(12)
                							.addGroup(layout.createParallelGroup(Alignment.BASELINE)
                								.addComponent(btnLeftDecel)
                								.addComponent(btnRightDecel)))
                						.addGroup(layout.createParallelGroup(Alignment.BASELINE)
                							.addComponent(btnDisconnect)
                							.addComponent(txtLog, GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)))
                					.addGap(239)))
                			.addContainerGap())
                );
                getContentPane().setLayout(layout);

                pack();
            }// </editor-fold>//GEN-END:initComponents

    private void btnLeftAccelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftAccelActionPerformed
        keybindingController.setLeftThrottle(keybindingController.accelerate(keybindingController.getLeftThrottle()));
        keybindingController.updateLabels();
    }//GEN-LAST:event_btnLeftAccelActionPerformed

    private void btnLeftDecelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftDecelActionPerformed
        keybindingController.setLeftThrottle(keybindingController.decelerate(keybindingController.getLeftThrottle()));
        keybindingController.updateLabels();
    }//GEN-LAST:event_btnLeftDecelActionPerformed

    private void btnRightAccelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightAccelActionPerformed
        keybindingController.setRightThrottle(keybindingController.accelerate(keybindingController.getRightThrottle()));
        keybindingController.updateLabels();
    }//GEN-LAST:event_btnRightAccelActionPerformed

    private void btnRightDecelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightDecelActionPerformed
        keybindingController.setRightThrottle(keybindingController.decelerate(keybindingController.getRightThrottle()));
        keybindingController.updateLabels();
    }//GEN-LAST:event_btnRightDecelActionPerformed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        
        communicator.connect();
        
        if (communicator.getConnected() == true)
        {
            if (communicator.initIOStream() == true)
            {
                communicator.initListener();
            }
        }
    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisconnectActionPerformed
        communicator.disconnect();
    }//GEN-LAST:event_btnDisconnectActionPerformed
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnConnect;
    public javax.swing.JButton btnDisconnect;
    public javax.swing.JButton btnLeftAccel;
    public javax.swing.JButton btnLeftDecel;
    public javax.swing.JButton btnRightAccel;
    public javax.swing.JButton btnRightDecel;
    @SuppressWarnings("rawtypes")
	public javax.swing.JComboBox cboxPorts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JLabel lblLeft;
    public javax.swing.JLabel lblRight;
    public javax.swing.JTextArea txtLog;
    private JTextField textField;
}
